const globalKeyEnum = Object.freeze({
    LIT_NODE_CLIENT: "LIT_NODE_CLIENT",
    CHAIN_WALLET: "CHAIN_WALLET",
    LIT_SESSION_SIGS: "LIT_SESSION_SIGS",
    YELLOW_STONE_WALLET:"YELLOW_STONE_WALLET",
    LIT_CONTRACTS:"LIT_CONTRACTS",
    PKP:"PKP"
})

module.exports = globalKeyEnum